services:
  - type: web
    name: linelink-finder
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: false